# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Snack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snack
  pod 'RxSwift', '6.2.0'
  pod 'RxCocoa', '6.2.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Then'
  pod 'ProgressHUD'
  pod 'RxDataSources', '~> 5.0'
  pod 'Alamofire', '~> 5.5'
  pod 'SwiftKeychainWrapper'
  pod 'InputBarAccessoryView'
  pod 'PasscodeKit'
  pod 'StompClientLib'
  pod 'MessageKit'

  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'

end
