server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/[your_DB]

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
