server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/lastpunch
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

jwt:
  secret: lastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunchlastpunch
